/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nicknathan' at '10/14/17 10:48 AM' with Gradle 2.6
 *
 * @author nicknathan, @date 10/14/17 10:48 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
